### PR TITLE
Added rotate option

### PR DESCRIPTION
**Pull request by amereii**
Similar to https://github.com/fleaflet/flutter_map/pull/864 I added rotate option to flutter_map_marker_popup

### CODE REVIEW

**Comment by amereii** [comment]
See https://github.com/lpongetti/flutter_map_marker_cluster/pull/73 too that waited for this PR

**Review by rorystephenson — COMMENTED** [review]
Thank you for the contribution @amereii!

I've tried it out locally, here the results:
 * The popup and the markers rotate with the map, maybe that was the intention although to me it feels more natural that the popup and the marker icon should not change orientation, only the map itself? That way you can still easily read what is in the popup.
 * When using snap to map (e.g. snapMapBottom) it throws an exception:
 
 ```
 The following assertion was thrown building MarkerPopup(dirty, state: _MarkerPopupState#98aba):
'package:flutter/src/widgets/basic.dart': Failed assertion: line 3709 pos 15: 'left == null || right == null || width == null': is not true.

The relevant error-causing widget was: 
  MarkerPopup file:///Users/rorystephenson/code/flutter/sources/flutter_map_marker_popup/lib/src/popup_marker_layer.dart:80:11
When the exception was thrown, this was the stack: 
#2      new Positioned (package:flutter/src/widgets/basic.dart:3709:15)
#3      _MarkerPopupState.build (package:flutter_map_marker_popup/src/marker_popup.dart:79:12)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
```

Apart from that there are some little style tweaks to make for consistency but that can come later.

**Comment by amereii** [comment]
@rorystephenson I will fix it ASAP, I'm too busy now

**Comment by rorystephenson** [comment]
Hi @amereii . In PR #21 I've added nullsafety support as well as rotation and many other improvements.

I have to wait until flutter_map merges null safety to master but when they do I will merge it.

Thanks for your contribution!!

If you have any comments or ideas for improving my implementation please let me know!

**Pull request closed without merging**
