### PR TITLE
Nullsafety

### LINKED ISSUE #15: Null safety migration
Hello, is Null safety migration on roadmap?
Thanks you

### PR DESCRIPTION
**Pull request by bsneider**
closes #15

### CODE REVIEW

**Review by rorystephenson — COMMENTED** [review]
Thank you very much for opening this @bsneider ! I really appreciate it.

It looks like the main `flutter_map` repo is close to releasing null safety. They are just waiting on `flutter_image` null-safety to be release and it seems to be very close.

For that reason I'm tempted to wait a little bit instead of using the forked version of `flutter_map`. When it's released we can just switch the dependency and I will give this PR another look.

**Comment by bsneider** [comment]
Yes, please wait. To be able to begin upgrading marker cluster this package also needed to be updated. I think, ideally, both should await flutter_map unless they have prerelease nullsafety branches. Flutter_map is awaiting flutter_image which is lacking in official maintainers.

**Comment by LavTeamProject** [comment]
> Yes, please wait. To be able to begin upgrading marker cluster this package also needed to be updated. I think, ideally, both should await flutter_map unless they have prerelease nullsafety branches. Flutter_map is awaiting flutter_image which is lacking in official maintainers.

Hello.
NullSafety branch

  flutter_map:
    git:
      url: git://github.com/fleaflet/flutter_map.git
      ref: issues/829-nullsafety

**Comment by bsneider** [comment]
> > Yes, please wait. To be able to begin upgrading marker cluster this package also needed to be updated. I think, ideally, both should await flutter_map unless they have prerelease nullsafety branches. Flutter_map is awaiting flutter_image which is lacking in official maintainers.
> 
> Hello.
> NullSafety branch
> 
> flutter_map:
> git:
> url: git://github.com/fleaflet/flutter_map.git
> ref: issues/829-nullsafety

updated. Example now runs with nullsafety. @LavTeamProject  please review updated PR, and manually test if possible

**Comment by rorystephenson** [comment]
Hey @bsneider. I really appreciate the effort you put in here, it got me really stoked to have someone else contributing :).

Recently I started looking at handling map rotation with this plugin which led down a big rabbit-hole where I needed to use the latest version of flutter_map and do some major refactoring. I decided to make it null-safe at the same time so there is now a PR with null-safety + rotation support and many other improvements/refactorings.

So I think it doesn't make sense to keep this PR open.

Thanks for the extra motivation and the time you spent!

**Pull request closed without merging**
