### PR TITLE
Add flutter_map 7.0.0 support

### PR DESCRIPTION
**Pull request by pento**
This is the only issue I've come across whilst testing the upcoming flutter_map release, hopefully it's going to be a fairly straightforward release. 🙂

### CODE REVIEW

**Comment by 22-David** [comment]
Are there any updates on this? :)

**Comment by pento** [comment]
I've tested this against the flutter_map 7.0.0 release, it all appears to be working (including the flutter_map_marker_popup demo app), so I've bumped the version in this PR to 7.0.0.

@rorystephenson: If you have a moment to check this out, that'd be super helpful!

**Comment by Albert221** [comment]
@rorystephenson hey, could we merge and release this? It's very small but blocking other (`flutter_map_marker_cluster`) package

**Comment by arthurjgs** [comment]
Hello, can we merge this asap because it's blocking the flutter_map_marker_cluster package :)

**Comment by Albert221** [comment]
@rorystephenson 🎉, thanks!

**Comment by rorystephenson** [comment]
New release just pushed. Apologies for the delay everyone and thanks for the contribution @pento .

**Comment by pento** [comment]
Glad I could help, @rorystephenson! 🙂

**Pull request merged**
