### PR TITLE
Nullsafety v2

### PR DESCRIPTION
**Pull request by rorystephenson**
This includes null safety support as well as some big upgrades:

 * Handle rotation.
 * Many bug fixes
 * An example app that lets you dynamically change all of the options to try it out
 * Update to the latest version of flutter_map.
 * Many others... I will try to sum it up better when I create a release and add to the CHANGELOG.md.

### CODE REVIEW

**Comment by bmason8** [comment]
Is there any plan to replace the '**latlong**' package with one of the newer latlong packages like '**latlong2**? I'm having an issue (that I suspect others might have) where '**latlong: 0.6.1'** depends on **logging >=0.11.3 <1.0.0** but **build_runner >=2.0.0** depends on **logging ^1.0.0**.
Thanks, I appreciate the work on this package and look forward to the updates in this PR.

**Comment by rorystephenson** [comment]
Good point! Actually I can remove the latlong dependency from this package since it's not using it directly anymore. I will do that when I get a chance (not at my computer right now).

**Comment by rorystephenson** [comment]
@bmason8 that's pushed now :).

**Comment by bmason8** [comment]
> @bmason8 that's pushed now :).

Thank you!

**Comment by sbu-WBT** [comment]
`flutter_map: ^0.13.0` is released with null safety so this can get merged

**Comment by rorystephenson** [comment]
> `flutter_map: ^0.13.0` is released with null safety so this can get merged

I saw that it has been released 🥳 ! Howeeeever there is a major bug that causes the example app (and probably any app) to crash as soon as you move the map: https://github.com/fleaflet/flutter_map/pull/923 .

**Comment by danielocampo2** [comment]
@rorystephenson `flutter_map: ^0.13.1` has been released with the fix

**Comment by rorystephenson** [comment]
> @rorystephenson `flutter_map: ^0.13.1` has been released with the fix

Did you notice the last two commits?

**Pull request merged**
